# Generated by Django 3.2.3 on 2021-08-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(blank=True, max_length=200, null=True)),
                ('club_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('club_img_url', models.CharField(blank=True, max_length=500, null=True)),
                ('club_logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('established', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
                ('deadline', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('sns_link', models.CharField(blank=True, max_length=500, null=True)),
                ('form_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubTypes',
            fields=[
                ('club_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_type_name', models.IntegerField(blank=True, null=True)),
                ('club_type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('club_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitment_content', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.CharField(max_length=3000)),
                ('post_introduce', models.CharField(blank=True, max_length=200, null=True)),
                ('post_img_url', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post.clubs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.authuser')),
            ],
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='post.clubtypes'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post.authuser'),
        ),
    ]
