# Generated by Django 3.2.3 on 2021-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='deadline',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='end_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='established',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
