# Generated by Django 3.2.3 on 2021-08-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210813_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post.clubtypes'),
        ),
    ]
