# Generated by Django 3.2.3 on 2021-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_clubs_recruitment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='club_detail_id',
            field=models.IntegerField(null=True),
        ),
    ]
